FROM php:7.4-apache

# COPY unidad_6 /var/www/html/

# Instalando node
RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \
    && apt-get install -y nodejs \
    && apt-get install --yes build-essential

RUN npm install -g firebase-tools@12.8.1

USER root
