name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Gracias por colaborar con tu primer Issue, si ya sabes la solución, te invitamos a compartir tu PR'
        pr-message: 'Gracias por mejorar este repo, estaremos atentos a este y proximos PR'
